### ISSUE TITLE
net-ftp in Gemified in 3.1

### ISSUE THREAD

**Issue by znz** [janlelis/stdgems#14]
net-ftp is [NEW BUNDLED GEMS](https://stdgems.org/new-in/3.1/#new-bundled-gems) only.
I think it should be in [DEFAULT GEMS REMOVED](https://stdgems.org/new-in/3.1/#default-gems-removed) too.

**Comment by janlelis** [comment]
Thanks, it's fixed now: https://stdgems.org/new-in/3.1/
