### ISSUE TITLE
License

### ISSUE THREAD

**Issue by taichi-ishitani** [janlelis/stdgems#23]
Hi,

I'm developing a gem to get version of default/bundled gem according to your JSON files.
https://github.com/taichi-ishitani/stdgems-version

My gem includes your JSON file so I'd like to know what license I should use for your JSON files.

**Comment by janlelis** [comment]
Hi Taichi,
thanks for reaching out, I have added a BSD license (to be close to Ruby's license).

https://github.com/taichi-ishitani/stdgems-version looks great, I've added a pointer to it in the README.
